### ISSUE TITLE
Index for abstract

### ISSUE THREAD

**Issue by Paldana99** [CRISalid-esr/svp-harvester#230]
For an abstract too long, the value of literal fields break the limit of the index that it is supported by db. 

> sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.ProgramLimitExceededError'>: index row requires 9296 bytes, maximum size is 8191

**Comment by jdp1ps** [comment]
Refacto : 
- remove abstracts from inheritance hierarchy
- convert abstract values tu SQLalchemy text type
