### ISSUE TITLE
Wikidata concept solver

### ISSUE THREAD

**Issue by jdp1ps** [CRISalid-esr/svp-harvester#281]
Ex. Concept https://www.wikidata.org/wiki/Q924713
ID du concept http://www.wikidata.org/entity/Q924713
URL du RDF : https://www.wikidata.org/wiki/Special:EntityData/Q924713.rdf

**Comment by Paldana99** [comment]
.rdf of wikidata have an issue with the parser: https://phabricator.wikimedia.org/T252731

As mentioned in: https://phabricator.wikimedia.org/R2307:7c9772244523eecd09381c77094773ea105044d5 We can use .ttl
