### ISSUE TITLE
Missing publications with openalex harvester

### ISSUE THREAD

**Issue by HDubernard** [CRISalid-esr/svp-harvester#583]
On OpenAlex, this researcher has 80 publications, https://api.openalex.org/authors/https://orcid.org/0000-0003-2185-709X 
Openalex harvester returns only 25 publications

**Comment by jdp1ps** [comment]
For query :
https://api.openalex.org/works?filter=author.orcid%3A0000-0003-2185-709X
The total number of result is 80 but there are only 25 results on the first page.

**Comment by HDubernard** [comment]
test ok
